import type { Metadata } from "next";
import "../styles/globals.css";
import { Domine, Gravitas_One, Limelight } from "next/font/google";
import { ToastContainer } from "react-toastify";

export const domine = Domine({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-domine",
});

export const gravitas = Gravitas_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-gravitas",
});

export const limelight = Limelight({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-limelight",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
        />

        <title>App User</title>
      </head>
      <body
        className={`${domine.variable} ${gravitas.variable} ${limelight.variable}`}
      >
        <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          closeOnClick
          pauseOnHover
          draggable
        />
        {children}
      </body>
    </html>
  );
}
